name: schedule-test-clean

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"  # UTC 4:00 = 北京时间 12:00

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo time
        run: echo "schedule test $(date)"
